### ISSUE TITLE
Inconsistency of titles in the terminal 

### ISSUE THREAD

**Issue by batunpc** [saminarp/rwar#1]
When you run the project it outputs the titles of the text files inconsistently on the terminal, even though the html generated and everything else is working perfectly. There are some in all upper cases and some in all lower cases as displayed on the terminal. 
### See here : 
<img width="587" alt="CleanShot 2022-09-16 at 03 46 28@2x" src="https://user-images.githubusercontent.com/71259399/190585163-9aa6e48a-c60d-456e-9f5d-33d79c71f770.png">

**Comment by saminarp** [comment]
Thank you for pointing this out. Have fixed it just now.
