### ISSUE TITLE
 Support --config with Config File

### ISSUE THREAD

**Issue by batunpc** [saminarp/rwar#11]
Hey there! :octocat: 

 I will be adding the config file to specify all of the potential `SSG options/flags` in a `JSON` formatted configuration file instead of having to pass them all as command line arguments every time.

- [x] The -c or --config flags accept a file path to a JSON config file.
- [x] If the file is missing, or can't be parsed as JSON, exit with an appropriate error message.
- [x] If the -c or --config option is provided, ignore all other options (i.e., a config file overrides other options on the command line).
- [x] The program should ignore any options in the config file it doesn't recognize. For example, if the SSG doesn't support stylesheets, ignore a stylesheet property.
- [x] If the config file is missing any options, assume the usual defaults. For example, use dist/ as the output directory if it isn't specified.

> I will go in order and check these boxes as I do

**Comment by saminarp** [comment]
moved to https://github.com/saminarp/rwar/pull/12

**Comment by saminarp** [comment]
Thank you so much!
