### ISSUE TITLE
Logo in the Readme shall not remain in the actual repository 

### ISSUE THREAD

**Issue by batunpc** [saminarp/rwar#5]
The logo in the README can be embedded from [an Imgur url](https://imgur.com/) instead of having a separate folder for it within the repository. See on [mine](https://github.com/batunpc/palpatine). While the folder size is fairly small, it still is unnecessary for the one to download the repo along with image folder that is not related with project.

**Comment by saminarp** [comment]
Thanks for this suggestion. The issue is fixed!
